I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/mechanics/styles.rpy", line 31, in script
    define config.side_image_layer = "side"
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
Exception: config.side_image_layer is not a known configuration variable.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/mechanics/styles.rpy", line 31, in script
    define config.side_image_layer = "side"
  File "/Users/nichosantos/Documents/[CODING]/renpy-8.2.3-sdk/renpy/ast.py", line 2248, in execute
    self.set()
  File "/Users/nichosantos/Documents/[CODING]/renpy-8.2.3-sdk/renpy/ast.py", line 2266, in set
    ns.set(self.varname, value)
  File "renpy/common/000namespaces.rpy", line 34, in set
    setattr(self.nso, name, value)
  File "/Users/nichosantos/Documents/[CODING]/renpy-8.2.3-sdk/renpy/defaultstore.py", line 101, in __setattr__
    raise Exception('config.%s is not a known configuration variable.' % (name))
Exception: config.side_image_layer is not a known configuration variable.

macOS-13.4-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
PLEASE IM BEGGING YOU 1.0
Thu May  8 01:41:19 2025
